// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOGrdfM4qxPzakaODJGlPZxUK7A2SaNus',
    appId: '1:856087418354:web:47a775a4bf5ac1da68476b',
    messagingSenderId: '856087418354',
    projectId: 'homeservice-bba23',
    authDomain: 'homeservice-bba23.firebaseapp.com',
    storageBucket: 'homeservice-bba23.appspot.com',
    measurementId: 'G-V8BNXR7MNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdMgHyEEvU1FFER8GmXrM3yV-MtOGSdc0',
    appId: '1:856087418354:android:f60722330612270168476b',
    messagingSenderId: '856087418354',
    projectId: 'homeservice-bba23',
    storageBucket: 'homeservice-bba23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB5VN3gzEHRpMntlqvY5Czd24dDJkkzMI',
    appId: '1:856087418354:ios:7c75f392a7dbb47c68476b',
    messagingSenderId: '856087418354',
    projectId: 'homeservice-bba23',
    storageBucket: 'homeservice-bba23.appspot.com',
    iosClientId: '856087418354-9jc878q279t74j472m98a921qrih6vup.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB5VN3gzEHRpMntlqvY5Czd24dDJkkzMI',
    appId: '1:856087418354:ios:7c75f392a7dbb47c68476b',
    messagingSenderId: '856087418354',
    projectId: 'homeservice-bba23',
    storageBucket: 'homeservice-bba23.appspot.com',
    iosClientId: '856087418354-9jc878q279t74j472m98a921qrih6vup.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyp',
  );
}
